### ISSUE TITLE
IME bug when typing Chinese characters

### ISSUE THREAD

**Issue by Chaojimengnan** [emilk/egui#4209]
**Describe the bug**

Unable to generate Chinese characters correctly, please see the following gif

Expect (test in `0.26.2`): 

![0](https://github.com/emilk/egui/assets/51994883/bd338cc5-5828-4e95-8c76-027daae4d9ea)

Bug (test in `latest`):

![1](https://github.com/emilk/egui/assets/51994883/cb67124d-86f8-4dc0-8928-6105346ba569)

**To Reproduce**
1. typing chinese characters on `text_edit_multiline` or `text_edit_singleline`

**Additional context**

It seems https://github.com/emilk/egui/commit/385daeb354fe10dc0bf968c760b9be7437684d49 break something.

**Comment by rustbasic** [comment]
I think it was resolved with #4210.

**Comment by Chaojimengnan** [comment]
> @Chaojimengnan
> 
> I think it was resolved with #4210.

Thanks for the quick fix, but bug still exist.

**Comment by rustbasic** [comment]
@Chaojimengnan 

You may need to compile it after running cargo update as follows.

```
cargo update
```

**Comment by Chaojimengnan** [comment]
> @Chaojimengnan
> 
> You may need to compile it after running cargo update as follows.
> 
> ```
> cargo update
> ```

yes, but bug still exist. 
it works correctly when I remove the following line
https://github.com/rustbasic/egui/blob/b689576c7d9ec16a334275a41dbc06198ac195fe/crates/egui/src/widgets/text_edit/builder.rs#L957-L958

**Comment by rustbasic** [comment]
@Chaojimengnan 

Please check if this fix works.

```rust
                    if !prediction.is_empty()
                        && cursor_range.secondary.ccursor.index
                            == state.ime_cursor_range.secondary.ccursor.index
                    {
```

**Comment by Chaojimengnan** [comment]
> @Chaojimengnan
> 
> Please check if this fix works. Maybe you can do it like this. Please let me know the results.
> 
> ```rust
>                     if !prediction.is_empty()
>                         && cursor_range.secondary.ccursor.index
>                             == state.ime_cursor_range.secondary.ccursor.index
>                     {
> ```
> 
> * [Fix: IME bug when typing Chinese characters #4210](https://github.com/emilk/egui/pull/4210)

Thank you. It's working correctly now.

**Comment by rustbasic** [comment]
@Chaojimengnan 

great. thank you
(This was my first time seeing a Chinese input scene.)
